terminal_programs:
  curl:
    weight: 1
    label: cURL
    lexer: sh
    icon: curl
    run_command: 'sh {filename}'
  cli:
    label: CLI
    lexer: sh
    linkable: false

languages:
  javascript:
    weight: 2
    label: JavaScript
    lexer: javascript
    icon: javascript
    dependencies:
      - 'nexmo'

  node:
    weight: 2
    label: Node.js
    lexer: javascript
    icon: node
    dependencies:
      - 'nexmo'
    run_command: 'node {filename}'

  java:
    weight: 3
    label: Java
    lexer: java
    unindent: true
    icon: java
    dependencies:
      - 'com.nexmo:client:@latest'

  dotnet:
    weight: 4
    label: .NET
    lexer: c#
    unindent: true
    icon: dotnet
    dependencies:
      - 'Nexmo.Csharp.Client'
  csharp:
    weight: 4
    label: .NET
    lexer: c#
    unindent: true
    icon: dotnet
    dependencies:
      - 'Nexmo.Csharp.Client'

  php:
    weight: 5
    label: PHP
    lexer: php
    icon: php
    dependencies:
      - 'nexmo/client'
    run_command: 'php {filename}'

  python:
    weight: 6
    label: Python
    lexer: python
    icon: python
    dependencies:
      - 'nexmo'
    run_command: 'python {filename}'

  ruby:
    weight: 7
    label: Ruby
    lexer: ruby
    icon: ruby
    dependencies:
      - 'nexmo'
    run_command: 'ruby {filename}'

  kotlin:
    weight: 8
    label: Kotlin
    lexer: java
    icon: android
    dependencies: []

  android:
    weight: 9
    label: Java
    lexer: java
    icon: android
    dependencies: []

  swift:
    weight: 10
    label: Swift
    lexer: swift
    icon: ios
    dependencies: []

  objective_c:
    weight: 11
    label: Objective-C
    lexer: ObjectiveC
    icon: ios
    dependencies: []

platforms:
  ios:
    languages:
      - swift
      - objective_c
  android:
    languages:
      - java
  web:
    languages:
      - javascript

data:
  ncco:
    label: NCCO
    lexer: json
    linkable: false
  json:
    weight: 1
    label: JSON
    lexer: json
    linkable: false
  xml:
    weight: 2
    label: XML
    lexer: xml
    linkable: false
