version: 2
updates:
- package-ecosystem: bundler
  directory: "/lib/nexmo_developer"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - rails-app-updates
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - gemspec-updates
