title: Making an app to app voice call
description: You make a phone call from a web app to another web app.
products:
  - client-sdk

introduction: 
  title: Introduction to this task
  description: This task shows you how to use make a voice call from a web app to another web app using the JavaScript Client SDK.
  content: |
    # Introduction
    In this tutorial, you will learn how to create a Client SDK application and then write the code to make a 
    phone call from your web app to another web app.

    To achieve this, you will create:

    * A web application that will make the app to app voice call using the Client SDK.
    * A webhook server that can process an inbound webhook and return an <abbr title="Nexmo Call Control Object">NCCO</abbr> to forward the inbound voice call to the destination app.

    When the in-app call is triggered from your application, Nexmo will make a request to your webhook server. You then use an NCCO and forward the call to the destination app.


prerequisites:
- create-nexmo-account
- install-nodejs
- install-node-client-sdk
- install-nexmo-cli-beta
- install-express
- run-ngrok

tasks:
- client-sdk/create-application
- client-sdk/create-users
- client-sdk/generate-jwts
- client-sdk/app-to-app/create-webhook-server
- client-sdk/app-to-app/call-code
- client-sdk/app-to-app/receive-code
- client-sdk/app-to-app/run

conclusion:
  title: What's next?
  description: What else can you do with the Client SDK?
  content: |

    # What's next?
    You can do a lot more with the Client SDK.

    We want to hear what ideas you have in mind? Contact us at [devrel@nexmo.com](mailto:devrel@nexmo.com)

    See [Client SDK documentation](/client-sdk/overview).
