library:
  initialization:
    basic:
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/initialize/basic.js'
      php:
        source: '.repos/nexmo-community/nexmo-php-quickstart/initialize/basic.php'
        from_line: 3
      java:
        source: '.repos/nexmo-community/nexmo-java-quickstart/src/main/java/com/nexmo/quickstart/initialize/BasicAuth.java'
        from_line: 18
        to_line: 19
        unindent: true
      ruby:
        source: '.repos/nexmo-community/nexmo-ruby-quickstart/initialize/basic.rb'
      python:
        source: '.repos/nexmo-community/nexmo-python-quickstart/initialize/basic.py'
      dotnet:
        source: '.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Authentication/BasicAuth.cs'
        from_line: 13
        to_line: 17
        unindent: true
    application:
      php:
        source: '.repos/nexmo-community/nexmo-php-quickstart/initialize/application.php'
        from_line: 3
      java:
        source: '.repos/nexmo-community/nexmo-java-quickstart/src/main/java/com/nexmo/quickstart/initialize/ApplicationAuth.java'
        from_line: 17
        to_line: 24
        unindent: true
      python:
        source: '.repos/nexmo-community/nexmo-python-quickstart/initialize/application.py'
    full:
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/initialize/full.js'
      ruby:
        source: '.repos/nexmo-community/nexmo-ruby-quickstart/initialize/full.rb'
      java:
        source: '.repos/nexmo-community/nexmo-java-quickstart/src/main/java/com/nexmo/quickstart/initialize/FullAuth.java'
        from_line: 24
        to_line: 29
        unindent: true
      python:
        source: '.repos/nexmo-community/nexmo-python-quickstart/initialize/full.py'
messaging:
  sms:
    send:
      curl:
        source: '_examples/curl/messaging/sms/send-an-sms.sh'
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/sms/send.js'
        from_line: 14
      java:
        source: '.repos/nexmo-community/nexmo-java-quickstart/src/main/java/com/nexmo/quickstart/sms/SendMessage.java'
        from_line: 44
        to_line: 50
        unindent: true
      csharp:
        source: '.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Controllers/SMSController.cs'
        from_line: 32
        to_line: 39
        unindent: true
      php:
        source: '.repos/nexmo-community/nexmo-php-quickstart/sms/send-sms.php'
        from_line: 8
        to_line: 12
      python:
        source: '.repos/nexmo-community/nexmo-python-quickstart/sms/__init__.py'
      ruby:
        source: '.repos/nexmo-community/nexmo-ruby-quickstart/sms/send.rb'
        from_line: 15
      python:
        source: '.repos/nexmo-community/nexmo-python-quickstart/sms/send-an-sms.py'
        from_line: 16
      dotnet:
        source: '.repos/nexmo-community/nexmo-dotnet-quickstart/NexmoDotNetQuickStarts/Controllers/SMSController.cs'
        from_line: 34
        to_line: 39
        unindent: true
    delivery-receipts:
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/sms/dlr-express.js'
      ruby:
        source: '.repos/nexmo-community/nexmo-ruby-quickstart/sms/delivery_receipt.rb'
      python:
        source: '.repos/nexmo-community/nexmo-python-quickstart/sms/dlr-flask.py'
      php:
        source: '.repos/nexmo-community/nexmo-php-quickstart/sms/receive-delivery-receipt-slim/index.php'
      java:
        source: '.repos/nexmo-community/nexmo-java-quickstart/src/main/java/com/nexmo/quickstart/sms/ReceiveDLR.java'
        from_line: 12
        to_line: 35
        unindent: true
    inbound:
      node:
        source: '.repos/nexmo-community/nexmo-node-quickstart/sms/receive-express.js'
      ruby:
        source: '.repos/nexmo-community/nexmo-ruby-quickstart/sms/receive.rb'
      python:
        source: '.repos/nexmo-community/nexmo-python-quickstart/sms/receive-flask.py'
      php:
        source: '.repos/nexmo-community/nexmo-php-quickstart/sms/receive-with-slim/index.php'
      java:
        source: '.repos/nexmo-community/nexmo-java-quickstart/src/main/java/com/nexmo/quickstart/sms/ReceiveSMS.java'
        from_line: 15
        to_line: 42
        unindent: true
number_insight:
  standard:
    curl:
      source: '_examples/curl/number_insight/standard.sh'
  async:
    curl:
      source: '_examples/curl/number_insight/async.sh'
      
