#!/bin/sh

remote_url="$2"
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$remote_url" == 'git@github.com:Nexmo/nexmo-developer.git' ]
then
  if echo $current_branch | grep -E '^private' > /dev/null
  then
    echo "You're about to push a private branch to a public repository, is that what you intended? [y|n]"
    read -n 1 -r < /dev/tty

    echo
    if echo $REPLY | grep -E '^[Yy]$' > /dev/null
    then
      exit 0 # push will execute
    else
      exit 1 # push will not execute
    fi
  fi
fi

exit 0
