opt_in_rules:
- attributes
- closing_brace
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- colon
- comma
- compiler_protocol_init
- control_statement
- cyclomatic_complexity
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure	
- explicit_init
- explicit_top_level_acl
- file_length
- first_where
- for_where
- identifier_name
- implicit_getter
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_nsgeometry_functions
- let_var_whitespace
- object_literal
- opening_brace
- operator_whitespace
- overridden_super_call
- prohibited_super_call
- protocol_property_accessors_order
- unused_optional_binding
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_optional_initialization
- redundant_string_enum_value
- redundant_void_return
- return_arrow_whitespace
- shorthand_operator
- statement_position
- syntactic_sugar
- trailing_comma
- trailing_semicolon
- unneeded_parentheses_in_closure_argument
- unused_closure_parameter
- unused_enumerated
- unused_optional_binding
- vertical_whitespace
- void_return
disabled_rules:
- mark
- trailing_whitespace
- file_header
- extension_access_modifier
- switch_case_on_newline
- functional_body_length
- explicit_type_interface
- todo
- line_length
- force_cast
- cyclomatic_complexity
- fatal_error_message
- function_body_length
- closure_end_indentation
- file_length
- identifier_name
- empty_count
- type_name
- nesting
- type_body_length
- empty_enum_arguments
- operator_whitespace
- attributes
- operator_usage_whitespace
excluded:
  - Carthage
  - Pods
  - Build
  - DerivedData
  - docs
  - Fastlane
  - mocket-io
  - ModuleCache
  - Scripts
  - ConversationDemo
  - ConversationDemoTests
  - ConversationDemoUITests
  - NexmoConversationE2ETests
  - NexmoConversationHermeticTests
  - Playgrounds