name: Lighthouse Audit
on: [deployment_status, workflow_dispatch]

jobs:
  lighthouse-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: mkdir -p ./tmp/artifacts
      - name: Lighthouse Audit
        uses: fabianrbz/github-action-lighthouse-heroku@master
        with:
          urls: '/,/concepts/overview,/api/verify'
          outputDirectory: ./tmp/artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEROKU_AUTH_TOKEN: ${{ secrets.HEROKU_AUTH_TOKEN }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: ./tmp/artifacts
